### ISSUE TITLE
Matlab 2021a crash to exist when using this

### ISSUE THREAD

**Issue by wonderkismet** [xiangruili/uiFileDnD#1]
sometimes work, but sometimes entire matlab crash when using this

**Comment by xiangruili** [comment]
When Matlab crashes, it normally saves a crash log into `pwd`. The log may provide some information for debugging. Can you check and post the crash log?

**Comment by tomjensen2** [comment]
> sometimes work, but sometimes entire matlab crash when using this

I had the same problem, fixed with 2021a update 4
