### ISSUE TITLE
Sorting of dropped files 

### ISSUE THREAD

**Issue by ivandemec** [xiangruili/uiFileDnD#5]
The dropped files order is shifted by 4 places e.g.
![image](https://github.com/xiangruili/uiFileDnD/assets/7983448/8b0b202c-e421-49ce-9ad2-b883e0b91dc9)

And on new insertion (in the same app instance) it gets shifted by 1 every time
![image](https://github.com/xiangruili/uiFileDnD/assets/7983448/dc3a1ee5-a634-4b44-ad92-6e48aa56dbf3)

As a work-around, one could resort the component contents afterwards, but could this be easily fixed?

P.S. Thanks a lot for your great work!

**Comment by xiangruili** [comment]
That is an interesting observation! It seems to me that order is determined by which file/folder the drag starts with. That one seems to be the first one always. My preference is to keep this OS behavior (there may be a reason for this kind of ordering?). You can easily to sort the names by yourself:

    names = sort(dat.names); % or reversing order if you prefer

**Comment by ivandemec** [comment]
Works like a charm!
Thanks a lot.
Best Regards
