### ISSUE TITLE
Matlab R2023a and so on...

### ISSUE THREAD

**Issue by EricMagalhaesDelgado** [xiangruili/uiFileDnD#6]
@xiangruili
It's an amazing idea! Listen... it seems that "enableDragAndDrop" and "enableDragAndDrop" methods for the webwindow object are not working on R2023a and R2023b. Did you test on those versions?

**Comment by xiangruili** [comment]
I tested on R2023b Windows 10, and it works well.
Are you under Linux? As noted in the code, enableDragAndDrop is no-op on any Matlab version I have tested so far under Linux.

**Comment by EricMagalhaesDelgado** [comment]
Wow... that is it! I just tested R2023b on both versions of Windows (10 and 11). It works well in Win10, but not on Win11. It seems that Windows 11 is blocking this behavior for Matlab... attached are images from the Windows 11 test (when entering the Matlab window, the mouse pointer shows a forbidden icon).

![image](https://github.com/xiangruili/uiFileDnD/assets/75496918/a34fce9e-0dd0-4a38-9721-6197c5d89740)
![image](https://github.com/xiangruili/uiFileDnD/assets/75496918/f92ba7d7-5c89-47bc-a0cd-86a26d6a059a)

**Comment by EricMagalhaesDelgado** [comment]
Mathworks already answered this question! It's not a Windows version issue, but how you are running Matlab (in my case, I was using runas in Windows 11 env). That's it. Sorry to bother you, your DnD is working fine!

https://www.mathworks.com/matlabcentral/answers/1805815-why-am-i-unable-to-open-a-script-function-by-drag-and-dropping-it-into-matlab-editor
